steps:
  # 1) 컨테이너 이미지 빌드
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/notam-454203/smartbriefier",
        "."
      ]

images:
  - gcr.io/notam-454203/smartbriefier