steps:
  # 1) 컨테이너 이미지 빌드
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/notam-454203/smartbriefier",
        "."
      ]

  # 2) Cloud Run 배포
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "smartbriefier",
        "--image",
        "gcr.io/notam-454203/smartbriefier",
        "--region",
        "asia-northeast3",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - gcr.io/notam-454203/smartbriefier
